version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agentic-explorer-db
    environment:
      POSTGRES_DB: agentic_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agentic-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: agentic-explorer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agentic-network

  # Backend API (for development)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentic-explorer-api
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@postgres:5432/agentic_explorer
      REDIS_URL: redis://redis:6379
      # Add your API keys here
      ALCHEMY_API_KEY: ${ALCHEMY_API_KEY}
      GRAPH_API_KEY: ${GRAPH_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - agentic-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  agentic-network:
    driver: bridge
