// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgybcbbsjdaolsrxrlkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRneWJjYmJzamRhb2xzcnhybGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDkwNDUsImV4cCI6MjA3MjgyNTA0NX0.simh2-euf-bgBCrc6f0YFY4DaN6IFFOVyZ_9yqgCFV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});